config/routes.rb
Demo::Application.routes.draw do
  resources :vehicles

  resources :people

  root :to => 'users#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  attr_accessible :city, :first_name, :last_name, :postal_code, :province, :street_address, :telephone, :user_id
  validates :province, :format => { :inclusion => %w(BC AB SK MB ON QC NB NL NS NT YT NU PE) }
  canadian_postal_code = /^[A-CEGHJK-NPR-TVXY][0-9][A-CEGHJK-NPR-TV-Z](\s)?[0-9][A-CEGHJK-NPR-TV-Z][0-9]$/
  validates :postal_code, :format => {:with => canadian_postal_code}
  validates :phone, :length => {exact: 10}
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province %><br />
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.number_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Street address</th>
    <th>City</th>
    <th>Province</th>
    <th>Postal code</th>
    <th>Telephone</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= person.street_address %></td>
    <td><%= person.city %></td>
    <td><%= person.province %></td>
    <td><%= person.postal_code %></td>
    <td><%= person.telephone %></td>
    <td><%= person.user_id %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Street address:</b>
  <%= @person.street_address %>
</p>

<p>
  <b>City:</b>
  <%= @person.city %>
</p>

<p>
  <b>Province:</b>
  <%= @person.province %>
</p>

<p>
  <b>Postal code:</b>
  <%= @person.postal_code %>
</p>

<p>
  <b>Telephone:</b>
  <%= @person.telephone %>
</p>

<p>
  <b>User:</b>
  <%= @person.user_id %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>