config/routes.rb
Demo::Application.routes.draw do
  resources :vehicles

  resources :people

  root :to => 'users#index'
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  attr_accessible :colour, :license_plate, :make, :model, :user_id, :year
  validate :license_plate, :presence => true
  validate :make, :presence => true
  # validate :year, :length => {:exact => 4}
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license_plate %><br />
    <%= f.text_field :license_plate %>
  </div>
  <div class="field">
    <%= f.label :colour %><br />
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <tr>
    <th>License plate</th>
    <th>Colour</th>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.license_plate %></td>
    <td><%= vehicle.colour %></td>
    <td><%= vehicle.make %></td>
    <td><%= vehicle.model %></td>
    <td><%= vehicle.year %></td>
    <td><%= vehicle.user_id %></td>
    <td><%= link_to 'Show', vehicle %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>License plate:</b>
  <%= @vehicle.license_plate %>
</p>

<p>
  <b>Colour:</b>
  <%= @vehicle.colour %>
</p>

<p>
  <b>Make:</b>
  <%= @vehicle.make %>
</p>

<p>
  <b>Model:</b>
  <%= @vehicle.model %>
</p>

<p>
  <b>Year:</b>
  <%= @vehicle.year %>
</p>

<p>
  <b>User:</b>
  <%= @vehicle.user_id %>
</p>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>